language: ruby
script: 'bundle exec rake'
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.3.0
  - ruby-head
env:
  - RUBY_PLATFORM="x86_64-linux"
  - RUBY_PLATFORM="x86_64-darwin11.3.0"
  - CODECLIMATE_REPO_TOKEN=91712672ab3a13c6201c11ea34ac37697a7758868a3b8fd0eddf9c03bde782af
before_install:
matrix:
  allow_failures:
    - rvm: ruby-head
  notifications:
    email:
      recipients:
        - ike18t@gmail.com
      on_success: change
      on_failure: change
