language: ruby
script: 'bundle exec rake'
cache: bundler
rvm:
  - 2.0.0
  - 2.3.0
  - ruby-head
env:
  - RUBY_PLATFORM="x86_64-linux"
  - RUBY_PLATFORM="x86_64-darwin11.3.0"
before_install:
matrix:
  allow_failures:
    - rvm: ruby-head
  notifications:
    email:
      recipients:
        - ike18t@gmail.com
      on_success: change
      on_failure: change
